# handlers/main.yml (упрощённый)
- name: Restart prometheus container
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true
  ignore_errors: true

- name: Restart compose stack
  ansible.builtin.command:
    cmd: docker-compose up -d --build
    chdir: "{{ app_dir }}"